# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish -c Release -o ./published

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
       name: build-artifacts
       path: ./published
  
    # deploy job
    deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v2
          with:
            name: build-artifacts

        - name: Deploy to github pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./published
            

